---
# handlers file for tamay.jira

- name: "Reload systemd"
  systemd:
    daemon-reload: yes
  listen: daemon_reload

- name: "Restart jira"
  service:
    name: jira-software
    state: restarted
    enabled: yes
  listen: restart_jira
